### PR TITLE
Refactor signup and profile pages

### LINKED ISSUE #40: Review CSS, HTML and refactor

### PR DESCRIPTION
**Pull request by jbinvnt**
Closes #40

### CODE REVIEW

**Comment by AdiNar1106** [comment]
Hey Joseph, is there any reason behind removing the glyphicons? Initially when they weren't there, the button styles didn't look nice, so I added those there and it looked much better.

**Comment by jbinvnt** [comment]
> 
> 
> Hey Joseph, is there any reason behind removing the glyphicons? Initially when they weren't there, the button styles didn't look nice, so I added those there and it looked much better.

Glyphicons aren't supported by the newest version of Bootstrap. The icons haven't been rendering since even before we submitted milestone 1 (I checked the screenshots to confirm this), so my change just removes the tags so we have cleaner code

**Comment by AdiNar1106** [comment]
Gotcha, then you're good to go. We have heroku set up to deploy every time there is a change in master. I will make sure nothing is broken. Go ahead and make the push!

**Review by AdiNar1106 — APPROVED** [review]
looks good!

**Pull request merged**
