### PR TITLE
Hp 5

### LINKED ISSUE #5: Create a patient profile page
This will involve copying the base HTML template and adding specific interface elements for the *patient profile*. See the patient section of the [pages planning doc](/docs/pages.md) for specifics.

### PR DESCRIPTION
**Pull request by AdiNar1106**
This pull request includes a page for Patients to create their profiles, and another page where patient profiles will be displayed based on their profile info, and drivers can select patients from this page. After merging this, I will use the template created by Joseph to adjust UI changes,

### CODE REVIEW

**Review by abhinavtripathy — APPROVED** [review]

**Comment by jbinvnt** [comment]
Before merging this, can you change the HTML files to use the template from #6 so that we can see how everything will look?

**Comment by jbinvnt** [comment]
@AdiNar1106 So far the patient profile page is using four different versions of Bootstrap. This is leading to undefined behavior in different browsers, and also it means that users are loading 4 times as much data as they should. I have opened an issue #9 to fix this, but I'm out of time to work on it tonight. I'll probably be able to finish it up tomorrow.

**Review by jbinvnt — CHANGES_REQUESTED** [review]
Wait to merge until I've completed issue #9 which integrates this with the template. Once that branch is merged into this one, the columns should work properly again and then we can merge this pull request also

**Comment by AdiNar1106** [comment]
Added patient profile UI pages and added custom healthpool css template

**Pull request merged**
