### PR TITLE
Hp 14 -> Added Navigation bar 

### PR DESCRIPTION
**Pull request by AdiNar1106**
Draft request to create a nav bar

### CODE REVIEW

**Comment by jbinvnt** [comment]
Great work on the navbar! Ultimately, I think that loading the navbar should be done through JavaScript rather than having it copied to each page. Otherwise if we make a single change to the navbar then we have to copy it to all of our HTML files. This means that this should be merged in Milestone 2, once we work on the JavaScript part. So for now I would suggest that we leave this open but don't merge it yet.

**Comment by AdiNar1106** [comment]
Good idea, but we might as well showcase it for this milestone, then we can have an issue reminding us to remove it and do it through JS. Otherwise the pages seem to blank, let me know!

**Comment by jbinvnt** [comment]
@AdiNar1106 Do you think we could just create a file called `navbar.html` with the code, and explain in the milestone document that it will be loaded into each file in the next milestone? If we have duplicate copies now it will make my current task of running the HTML validator more difficult.

**Comment by AdiNar1106** [comment]
@jbinvnt I don't mind doing that, but if we have to show a "complete" UI in this milestone, I thought it'd be worth having it on all pages for the time being, if it makes validation harder then we could make a separate file. Do we want to ask the TAs about it?

**Pull request closed without merging**
